# Pre-commit hooks for knots
# See https://pre-commit.com for more information

# Standard complexity check
- id: knots
  name: Code Complexity Check
  description: Check C code complexity with default thresholds (McCabe 15, Cognitive 15, Nesting 5, SLOC 50, ABC 10.0, Returns 3)
  entry: hooks/pre-commit-wrapper.sh
  language: script
  files: \.(c|h)$
  pass_filenames: true

# Verbose variant - shows summary for all files
- id: knots-verbose
  name: Code Complexity Check (Verbose)
  description: Show summary for all files, not just violations
  entry: hooks/pre-commit-wrapper.sh --verbose
  language: script
  files: \.(c|h)$
  pass_filenames: true

# Strict variant - stricter thresholds
- id: knots-strict
  name: Code Complexity Check (Strict)
  description: Strict thresholds (McCabe 10, Cognitive 10, Nesting 3, SLOC 30, ABC 5.0, Returns 3)
  entry: hooks/pre-commit-wrapper.sh
  language: script
  files: \.(c|h)$
  pass_filenames: true
  args: ['--mccabe-threshold=10', '--cognitive-threshold=10', '--nesting-threshold=3', '--sloc-threshold=30', '--abc-threshold=5.0', '--return-threshold=3']

# Test quality checker - validates tests have sufficient complexity and boundary coverage
# Designed for Ceedling framework - parses TEST_SOURCE_FILE macro to find source files
- id: test-complexity
  name: Test Quality Check (Complexity & Boundaries)
  description: Validate unit tests have sufficient cyclomatic complexity and boundary coverage
  entry: hooks/test-complexity-wrapper.sh
  language: script
  files: ^Test/test_.*\.c$
  pass_filenames: true
  require_serial: false
  stages: [commit]
